site_name: regexparser Docs

plugins:
  - mkdocstrings

theme:
  name: "material"

nav:
  - regexparser Documentation: index.md
  - reference.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
